[project]
name = "aresta-db"
version = "0.3.1-dev"
description = "Banco de dados e ecossistema de croquis de escalada Aresta"
readme = "README.md"
requires-python = ">=3.13, <3.14"  # Paddle-paddle não suporta 3.14
dependencies = []

[dependency-groups]

# Pipeline de compilação/deploy de croquis
deploy = [
    "pillow",
    "pyyaml",
    "protobuf",
    "grpcio-tools",
    "mypy-protobuf",
]

# Validador de pull requests da database
validador = [
    {include-group = "deploy"},
    "pygit2",
]

# Interface gráfica do Editor Aresta 
editor = [
    {include-group = "deploy"},
    "pyside6-essentials",
    "pyinstaller",
    "pytest-qt",
    "pygit2",
    "requests",
    "cryptography",
    "keyring",
    "qtawesome",
    "qrcode",
    "ruamel.yaml",
    "fastapi",
    "uvicorn",
    "httpx",
    "winrt-Windows.Services.Store; sys_platform == 'win32'",
    "winrt-Windows.ApplicationModel; sys_platform == 'win32'",
    "sentry-sdk>=2.68.1",
]

# Extração pesada de PDFS, IA e OCR
pdf = [
    "pymupdf",
    "paddleocr",
    "paddleocr[doc-parser]",
    "paddleocr[ie]",
    "graphviz",
    "boto3",
    "duckduckgo-search",
    "numpy",
]

# Suíte de testes e ferramentas de desenvolvimento
dev = [
    "pytest",
    "pytest-xdist",
    "pytest-testmon",
    "pytest-mock",
    "moto[s3]",
    "moto",
    "mypy>=1.15.0",
    "mypy-protobuf>=3.6.0",
    "types-requests",
    "types-PyYAML",
    "types-protobuf",
    "types-qrcode",
]


[tool.uv]
package = false
default-groups = ["deploy", "validador", "editor", "pdf", "dev"]

[tool.mypy]
python_version = "3.13"
mypy_path = ["."]
explicit_package_bases = true
strict = true
follow_imports = "silent"

disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
no_implicit_optional = true
warn_return_any = true
warn_unused_ignores = true
show_error_codes = true




[[tool.mypy.overrides]]
module = [
    "aresta_api.proto.generated.*",
    "beta_pb2",
    "croqui_pb2",
    "croqui_experimental_pb2",
    "indice_pb2",
    "serving_pb2",
]
ignore_errors = true
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = [
    "grpc_tools",
    "grpc_tools.*",
    "qtawesome",
    "qtawesome.*",
    "winrt.*",
    "paddleocr",
    "paddleocr.*",
    "fitz",
    "fitz.*",
    "pymupdf",
    "pymupdf.*",
    "duckduckgo_search",
    "duckduckgo_search.*",
    "graphviz",
    "graphviz.*",
    "boto3",
    "boto3.*",
    "botocore",
    "botocore.*",
]
ignore_missing_imports = true
disallow_untyped_calls = false






